const FilterActionTypes = {
  TOGGLE_FILTER_BUTTON: " TOGGLE_FILTER_BUTTON",
  FILTER_UNDER_HUND: "FILTER_UNDER_HUND",
  FILTER_ABOVE_HUND: "FILTER_ABOVE_HUND",
  RESTORE_STATE: "RESTORE_STATE",
};

export default FilterActionTypes;